# Generated by Django 3.2.7 on 2022-03-31 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experts',
            name='date_add',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата внесения в базу'),
        ),
        migrations.AlterField(
            model_name='experts',
            name='snils',
            field=models.CharField(default='000-000-000 00', max_length=20, unique=True, verbose_name='СНИЛС'),
        ),
        migrations.AlterField(
            model_name='experts',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус активности'),
        ),
    ]
