# Generated by Django 3.2.7 on 2022-03-31 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0047_alter_profile_user'),
        ('expert', '0002_auto_20220331_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='experts',
            name='mo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='applications.munobr', verbose_name='МО'),
        ),
    ]
