# Generated by Django 4.0.3 on 2022-04-15 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0052_alter_appcritcheck_app_alter_appcritfile_app_and_more'),
        ('expert', '0004_experts_subj'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='pos',
            field=models.ForeignKey(default=243, on_delete=django.db.models.deletion.CASCADE, to='applications.position', verbose_name='Должность'),
        ),
    ]
