# Generated by Django 4.0.3 on 2022-04-15 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0052_alter_appcritcheck_app_alter_appcritfile_app_and_more'),
        ('expert', '0005_marks_pos'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together={('pos', 'criteria')},
        ),
        migrations.AlterUniqueTogether(
            name='total',
            unique_together={('cat', 'pos')},
        ),
    ]
