# Generated by Django 4.0.3 on 2022-04-15 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0007_expertmarks_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertmarks',
            old_name='Mark',
            new_name='mark',
        ),
    ]
