# Generated by Django 4.0.3 on 2022-04-15 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0052_alter_appcritcheck_app_alter_appcritfile_app_and_more'),
        ('expert', '0008_rename_mark_expertmarks_mark'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expertmarks',
            unique_together={('app', 'expert', 'criteria')},
        ),
    ]
