# Generated by Django 4.0.3 on 2022-04-15 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0052_alter_appcritcheck_app_alter_appcritfile_app_and_more'),
        ('expert', '0009_alter_expertmarks_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appresult',
            unique_together={('expert', 'app')},
        ),
    ]
