# Generated by Django 4.0.3 on 2022-04-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0010_alter_appresult_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appresult',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Дата проведения экспертизы'),
        ),
    ]
