# Generated by Django 4.0.3 on 2022-04-16 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0053_stages'),
        ('expert', '0011_alter_appresult_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appresult',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expertresult', to='applications.apps', verbose_name='Заявка'),
        ),
    ]
