# Generated by Django 4.0.2 on 2022-02-10 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cat', models.CharField(max_length=250, verbose_name='Заявленная категория')),
            ],
            options={
                'verbose_name': 'Завяленная категория',
                'verbose_name_plural': 'Завяленные категории',
            },
        ),
        migrations.CreateModel(
            name='Attform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Форма аттестации')),
            ],
            options={
                'verbose_name': 'Форма аттестации',
                'verbose_name_plural': 'Формы аттестации',
            },
        ),
        migrations.CreateModel(
            name='Munobr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_mo', models.CharField(max_length=250, verbose_name='Наименование МО')),
                ('type_mo', models.CharField(max_length=100, verbose_name='Тип МО')),
            ],
            options={
                'verbose_name': 'МО',
                'verbose_name_plural': 'МО',
            },
        ),
        migrations.CreateModel(
            name='Periods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_period', models.CharField(max_length=30, verbose_name='Наименование периода')),
                ('date_start', models.DateField(verbose_name='Дата начала периода')),
                ('date_end', models.DateField(verbose_name='Дата окончания периода')),
            ],
            options={
                'verbose_name': 'Период',
                'verbose_name_plural': 'Периоды',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pos', models.CharField(max_length=150, verbose_name='Должность')),
                ('type_pos', models.CharField(max_length=20, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='type_oo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название типа ОО')),
            ],
            options={
                'verbose_name': 'Тип ОО',
                'verbose_name_plural': 'Типы ОО',
            },
        ),
        migrations.CreateModel(
            name='Oo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500, verbose_name='Полное наименование ОО')),
                ('short_name', models.CharField(max_length=150, verbose_name='Краткое наименование ОО')),
                ('address', models.TextField(verbose_name='Адрес ОО')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Телефон ОО')),
                ('email', models.CharField(max_length=254, verbose_name='Электронная почта ОО')),
                ('url', models.CharField(max_length=254, verbose_name='Сайт ОО')),
                ('mo', models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='applications.munobr', verbose_name='МО ОО')),
                ('type', models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='applications.type_oo', verbose_name='Тип ОО')),
            ],
            options={
                'verbose_name': 'ОО',
                'verbose_name_plural': 'ОО',
            },
        ),
    ]
