# Generated by Django 4.0.2 on 2022-02-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oo',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон ОО'),
        ),
    ]
