# Generated by Django 4.0.2 on 2022-02-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_oo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oo',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес ОО'),
        ),
        migrations.AlterField(
            model_name='oo',
            name='email',
            field=models.CharField(blank=True, max_length=254, verbose_name='Электронная почта ОО'),
        ),
        migrations.AlterField(
            model_name='oo',
            name='url',
            field=models.CharField(blank=True, max_length=254, verbose_name='Сайт ОО'),
        ),
    ]
