# Generated by Django 4.0.2 on 2022-02-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_oo_address_alter_oo_email_alter_oo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Предметная область')),
            ],
            options={
                'verbose_name': 'Предметная область',
                'verbose_name_plural': 'Предметные области',
            },
        ),
    ]
