# Generated by Django 4.0.2 on 2022-02-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_subjareas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cat', models.CharField(max_length=100, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
