# Generated by Django 4.0.2 on 2022-02-21 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_alter_apps_pos_alter_apps_subj_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cat_have',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile_cathave', to='applications.categories', verbose_name='Имеющаяся категория'),
        ),
    ]
