# Generated by Django 4.0.2 on 2022-02-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_apps_mo_apps_oo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_doc',
            field=models.DateField(default=None, null=True, verbose_name='Дата документа'),
        ),
        migrations.AddField(
            model_name='profile',
            name='name_doc',
            field=models.CharField(default=None, max_length=25, null=True, verbose_name='Номер документа'),
        ),
    ]
