# Generated by Django 4.0.2 on 2022-02-22 02:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_profile_date_doc_profile_name_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apps',
            name='email',
        ),
        migrations.RemoveField(
            model_name='apps',
            name='mo',
        ),
        migrations.RemoveField(
            model_name='apps',
            name='name',
        ),
        migrations.RemoveField(
            model_name='apps',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='apps',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='apps',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cat_have',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_doc',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='finish_cat',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name_doc',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='oo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='oo_exp',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pos_exp',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='start_cat',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subj_area',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='teach_exp',
        ),
        migrations.AddField(
            model_name='apps',
            name='date_doc',
            field=models.DateField(default=None, null=True, verbose_name='Дата документа'),
        ),
        migrations.AddField(
            model_name='apps',
            name='name_doc',
            field=models.CharField(default=None, max_length=25, null=True, verbose_name='Номер документа'),
        ),
        migrations.AddField(
            model_name='apps',
            name='oo_exp',
            field=models.PositiveIntegerField(default=0, verbose_name='Стаж работы в ОО'),
        ),
        migrations.AddField(
            model_name='apps',
            name='pos_exp',
            field=models.PositiveIntegerField(default=0, verbose_name='Стаж в должности'),
        ),
        migrations.AddField(
            model_name='apps',
            name='teach_exp',
            field=models.PositiveIntegerField(default=0, verbose_name='Педагогический стаж'),
        ),
        migrations.AlterField(
            model_name='apps',
            name='cat_have',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apps_cathave', to='applications.categories', verbose_name='Имеющаяся категория'),
        ),
        migrations.AlterField(
            model_name='apps',
            name='finish_cat',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Дата окончания действия атт. категории'),
        ),
        migrations.AlterField(
            model_name='apps',
            name='pos',
            field=models.ForeignKey(default=243, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apps_pos', to='applications.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='apps',
            name='start_cat',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Дата начала действия атт. категории'),
        ),
        migrations.AlterField(
            model_name='apps',
            name='subj_area',
            field=models.ForeignKey(default=194, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apps_subj', to='applications.subjareas', verbose_name='Предметная область'),
        ),
    ]
