# Generated by Django 4.0.2 on 2022-02-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_remove_apps_email_remove_apps_mo_remove_apps_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Критерий')),
                ('description', models.CharField(max_length=150, verbose_name='Наименование')),
                ('need_upload', models.BooleanField(default=False, verbose_name='Проверка необходимости загрузки файлов')),
            ],
            options={
                'verbose_name': 'Критерий',
                'verbose_name_plural': 'Критерии',
            },
        ),
    ]
