# Generated by Django 4.0.2 on 2022-02-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_criterias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterias',
            name='description',
            field=models.CharField(max_length=300, verbose_name='Наименование'),
        ),
    ]
