# Generated by Django 4.0.2 on 2022-02-24 01:41

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_alter_criterias_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterias',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='applications.criterias', verbose_name='Родитель'),
        ),
    ]
