# Generated by Django 4.0.2 on 2022-02-24 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_criterias_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criterias',
            options={},
        ),
    ]
