# Generated by Django 4.0.2 on 2022-02-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_alter_criterias_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterias',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criterias',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criterias',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criterias',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
    ]
