# Generated by Django 4.0.2 on 2022-02-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0027_alter_profile_birthday_alter_profile_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='name_pos',
            field=models.CharField(max_length=150, unique=True, verbose_name='Должность'),
        ),
    ]
