# Generated by Django 4.0.2 on 2022-02-28 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0029_alter_apps_finish_cat_alter_apps_start_cat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attcategories',
        ),
    ]
