# Generated by Django 4.0.2 on 2022-02-28 04:44

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0030_delete_attcategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poscriterias',
            name='crits',
            field=mptt.fields.TreeManyToManyField(related_name='crits_pos', to='applications.Criterias', verbose_name='Критерии'),
        ),
    ]
