# Generated by Django 4.0.2 on 2022-02-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0031_alter_poscriterias_crits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poscriterias',
            name='crits',
            field=models.ManyToManyField(related_name='crits_pos', to='applications.Criterias', verbose_name='Критерии'),
        ),
    ]
