# Generated by Django 4.0.2 on 2022-03-15 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0032_alter_poscriterias_crits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=100, verbose_name='Имя параметра')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметр',
            },
        ),
        migrations.CreateModel(
            name='Pc_pairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='applications.criterias', verbose_name='Критерий')),
                ('parameter', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='applications.parameters', verbose_name='Параметр')),
            ],
            options={
                'verbose_name': 'Пара Критерий-Параметр',
                'verbose_name_plural': 'Пары Критерий-Параметр',
            },
        ),
        migrations.CreateModel(
            name='Pc_values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=500, verbose_name='Значение')),
                ('app', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='applications.apps', verbose_name='Заявка')),
                ('pc_pair', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='applications.pc_pairs', verbose_name='Пара Критерий-Параметр')),
            ],
            options={
                'verbose_name': 'Пара Параметр-Значение',
                'verbose_name_plural': 'Пары Параметр-Значение',
            },
        ),
    ]
