# Generated by Django 4.0.2 on 2022-03-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0033_parameters_pc_pairs_pc_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='parameter_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Имя параметра'),
        ),
    ]
