# Generated by Django 4.0.2 on 2022-03-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0034_alter_parameters_parameter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='parameter_name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Имя параметра'),
        ),
    ]
