# Generated by Django 4.0.2 on 2022-03-17 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0038_appcritcheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critpars',
            name='criteria',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='applications.criterias', unique=True, verbose_name='Критерий'),
        ),
    ]
