# Generated by Django 4.0.2 on 2022-03-17 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0039_alter_critpars_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critpars',
            name='criteria',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='applications.criterias', verbose_name='Критерий'),
        ),
    ]
