# Generated by Django 4.0.2 on 2022-03-18 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0040_alter_critpars_criteria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appcritcheck',
            options={'verbose_name': 'Связь Заявка-Параметр', 'verbose_name_plural': 'Связи Заявки-Параметры'},
        ),
    ]
