# Generated by Django 4.0.2 on 2022-03-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0041_alter_appcritcheck_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcritparvalue',
            name='row',
            field=models.PositiveIntegerField(default=1, verbose_name='Строка'),
        ),
    ]
