# Generated by Django 4.0.2 on 2022-03-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0043_criterias_description_crit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterias',
            name='description_crit',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Информация к заполнению критерия'),
        ),
        migrations.AlterField(
            model_name='criterias',
            name='description_upload',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Информация к загружаемым документам'),
        ),
    ]
