# Generated by Django 4.0.3 on 2022-04-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0047_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Форма аттестации')),
            ],
            options={
                'verbose_name': 'Форма аттестации',
                'verbose_name_plural': 'Формы аттестации',
            },
        ),
    ]
