# Generated by Django 4.0.3 on 2022-04-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0049_delete_attforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oo',
            name='short_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Краткое наименование ОО'),
        ),
    ]
