# Generated by Django 4.0.3 on 2022-04-08 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0050_alter_oo_short_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Periods',
        ),
    ]
