# Generated by Django 4.0.3 on 2022-04-15 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0051_delete_periods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcritcheck',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appcrits', to='applications.apps', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='appcritfile',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='critfile', to='applications.apps', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='appcritparvalue',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='critdata', to='applications.apps', verbose_name='Заявка'),
        ),
    ]
