# Generated by Django 4.0.3 on 2022-04-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0052_alter_appcritcheck_app_alter_appcritfile_app_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_stage', models.CharField(default='', max_length=50, unique=True, verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Этап всестороннего анализа',
                'verbose_name_plural': 'Этапы всестороннего анализа',
            },
        ),
    ]
