# Generated by Django 4.0.3 on 2022-04-08 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0051_delete_periods'),
        ('expert', '0004_experts_subj'),
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=50, verbose_name='Результат экспертизы')),
                ('app', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='applications.apps', verbose_name='Заявка')),
                ('expert', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expert.experts', verbose_name='Эксперт')),
                ('period', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='operators.periods', verbose_name='Период')),
            ],
            options={
                'verbose_name': 'Распределение',
                'verbose_name_plural': 'Распределения',
            },
        ),
    ]
