# Generated by Django 4.0.3 on 2022-04-08 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0003_alter_distributions_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributions',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата создания назначения'),
        ),
    ]
