# Generated by Django 4.0.3 on 2022-04-15 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0052_alter_appcritcheck_app_alter_appcritfile_app_and_more'),
        ('operators', '0004_distributions_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributions',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appdistrib', to='applications.apps', verbose_name='Заявка'),
        ),
    ]
