# Generated by Django 4.0.3 on 2022-04-17 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0053_stages'),
        ('operators', '0006_remove_distributions_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributions',
            name='stage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='applications.stages', verbose_name='Этап всестороннего анализа'),
        ),
    ]
